// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiz8lhDse7WmYqHugI6-11J1pvJVH__EY',
    appId: '1:548742965784:web:8d39ac86af1a204b38716d',
    messagingSenderId: '548742965784',
    projectId: 'todoapp-6c2e9',
    authDomain: 'todoapp-6c2e9.firebaseapp.com',
    storageBucket: 'todoapp-6c2e9.firebasestorage.app',
    measurementId: 'G-THSNPTZ2GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlrNSRC0xjYy77CbLL12nEhw6EAa3d24I',
    appId: '1:548742965784:android:337cc4db63e3463938716d',
    messagingSenderId: '548742965784',
    projectId: 'todoapp-6c2e9',
    storageBucket: 'todoapp-6c2e9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiz8lhDse7WmYqHugI6-11J1pvJVH__EY',
    appId: '1:548742965784:web:467250fb040b21ba38716d',
    messagingSenderId: '548742965784',
    projectId: 'todoapp-6c2e9',
    authDomain: 'todoapp-6c2e9.firebaseapp.com',
    storageBucket: 'todoapp-6c2e9.firebasestorage.app',
    measurementId: 'G-PM5BT148DY',
  );
}
